spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PARKING_DB
    username: bagga
    password: 3asfour25102212
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
